apiVersion: 1
datasources:
  - name: LegionPG
    type: postgres
    access: proxy
    url: legion-postgres:5432
    user: legion
    secureJsonData:
      password: ${LEGION_DB_PASSWORD}
    jsonData:
      database: legion
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    editable: true
