apiVersion: 1
datasources:
  - name: LegionPG
    type: postgres
    access: proxy
    url: host.docker.internal:5433
    user: legion
    secureJsonData:
      password: ${LEGION_PG_PASSWORD}
    jsonData:
      database: legion
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    editable: true
