#!/usr/bin/env bash
# Commit the derived feature-map files build_feature_map.py just rewrote (hostcron ada-feature-map-nightly).
set -uo pipefail
cd /c/code/ADA || exit 1
HDR="GENERATED by scripts/architecture/build_feature_map.py"
paths=()
while IFS= read -r line; do
    st="${line:0:2}"; p="${line:3}"
    case "$p" in
        docs/architecture/features/*|docs/architecture/INDEX.md|docs/architecture/index.json|docs/architecture/inputs.json|docs/architecture/tables.json|docs/architecture/ownership.json)
            paths+=("$p") ;;
        */CLAUDE.md)
            if [[ "$st" == *D* ]]; then
                git show "HEAD:$p" 2>/dev/null | head -1 | grep -q "$HDR" && paths+=("$p")
            else
                head -1 "$p" 2>/dev/null | grep -q "$HDR" && paths+=("$p")
            fi ;;
    esac
done < <(git status --porcelain --untracked-files=all -- docs/architecture ':(glob)**/CLAUDE.md')
exec bash /c/code/shared-infra/scripts/ada-autocommit.sh \
    "Enhancement-1001108: nightly feature-map refresh" \
    "Regenerated by hostcron ada-feature-map-nightly (build_feature_map.py)" "${paths[@]}"
