#!/usr/bin/env python3
"""Render .env.example from every ${VAR} the compose files actually reference,
plus the infractl control-plane variables. Values are never copied from .env --
only names, grouped by the compose file that reads them, with the default
(if the compose file declares one) shown after `#`.

The previous hand-written .env.example described the LiteLLM stack retired on
2026-05-14 and was missing 24 of the 33 variables the live stack needs.

This gate would pass trivially if the compose files referenced no variables at
all; `--check` therefore also fails when fewer than 20 variables are found.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPOSE = sorted(ROOT.glob("docker-compose.*.yml")) + [ROOT / "pyroscope" / "docker-compose.pyroscope.yml"]
VAR_RE = re.compile(r"\$\{([A-Z][A-Z0-9_]*)(?::?[-?]([^}]*))?\}")

EXTRA = {
    "infractl (shared-infra-control)": [
        ("INFRACTL_TOKEN", "bearer token every caller (ADA, Legion, CLI) sends as X-Infractl-Token"),
        ("INFRA_PROBE_VK", "Bifrost virtual key used by probes/smoke scripts (claude-code-local); never a project key"),
        ("INFRA_GEMINI_API_KEYS", "comma-separated Google AI Studio keys for the infra brain (direct, never via Bifrost)"),
        ("INFRA_GEMINI_API_KEY_1", "additional rotation slots 1..5, one key per Google Cloud project"),
        ("INFRA_GEMINI_API_KEY_2", ""),
        ("INFRA_GEMINI_API_KEY_3", ""),
        ("INFRA_GEMINI_API_KEY_4", ""),
        ("INFRA_GEMINI_API_KEY_5", ""),
        ("INFRA_GEMINI_MODEL", "optional pin; default = newest gemini flash model the key can generateContent with"),
        ("INFRA_BRAIN_MAX_CALLS_PER_DAY", "hard cap on brain LLM calls (default 60)"),
        ("DISCORD_INFRA_WEBHOOK", "webhook on #shared-infra (reports, heals, meta-alerts)"),
        ("DISCORD_INFRA_CHANNEL_ID", "channel id of #shared-infra"),
        ("DISCORD_BOT_TOKEN", "optional bot token for richer posts (falls back to the webhook)"),
        ("LEGION_API_BASE", "Legion tracker base URL (default http://host.docker.internal:8005)"),
    ]
}


def collect() -> dict[str, list[tuple[str, str]]]:
    groups: dict[str, list[tuple[str, str]]] = {}
    seen: set[str] = set()
    for f in COMPOSE:
        if not f.exists():
            continue
        found: dict[str, str] = {}
        for m in VAR_RE.finditer(f.read_text(encoding="utf-8", errors="ignore")):
            name, default = m.group(1), (m.group(2) or "").strip()
            if name not in found:
                found[name] = default
        rows = [(n, d) for n, d in found.items() if n not in seen]
        seen.update(found)
        if rows:
            groups[f.name] = rows
    return groups


def render() -> str:
    groups = collect()
    out = [
        "# shared-infra .env.example -- GENERATED by scripts/render_env_example.py",
        "# Copy to .env and fill in. Names only; every variable below is read by the",
        "# compose file it is listed under (default after '#', if any). Regenerate after",
        "# any compose change: python scripts/render_env_example.py",
        "#",
        "# Stack: Bifrost LLM gateway (:4445) + qwen38-chat local vLLM (:18801) + vllm-embed",
        "# (:8001) + observability (Prometheus :9099, Alertmanager :9095, Grafana :3050,",
        "# Loki :3100, Tempo :3200) + searxng (:8091) + freellmapi (:3015) + the",
        "# shared-infra-control plane (:8095). LiteLLM was retired 2026-05-14.",
        "",
    ]
    for fname, rows in groups.items():
        out.append(f"# ---- {fname} ----")
        for name, default in rows:
            out.append(f"{name}=" + (f"   # default: {default}" if default and not default.startswith("?") else ""))
        out.append("")
    for title, rows in EXTRA.items():
        out.append(f"# ---- {title} ----")
        for name, note in rows:
            out.append(f"{name}=" + (f"   # {note}" if note else ""))
        out.append("")
    return "\n".join(out)


def main() -> int:
    text = render()
    n = sum(1 for l in text.splitlines() if re.match(r"^[A-Z][A-Z0-9_]*=", l))
    target = ROOT / ".env.example"
    if "--check" in sys.argv:
        if n < 20:
            print(f"only {n} variables found -- generator broken"); return 1
        if target.read_text(encoding="utf-8") != text:
            print("DRIFT: .env.example stale"); return 1
        print("up to date"); return 0
    target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote .env.example with {n} variables")
    return 0


if __name__ == "__main__":
    sys.exit(main())
