"""Render docs/PROVIDERS.md from bifrost/config.json + disabled-providers.json.

The provider list in prose docs drifted three times (CLAUDE.md, README.md and
ADA's 50-llm.md all named parked providers as active on 2026-09-25). This
file is GENERATED; the gate fails if it is stale (`--check`). Model names and
key COUNTS only -- never key values.

    python scripts/render_providers_doc.py          # rewrite docs/PROVIDERS.md
    python scripts/render_providers_doc.py --check  # exit 1 if out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "bifrost" / "config.json"
DISABLED = ROOT / "bifrost" / "disabled-providers.json"
OUT = ROOT / "docs" / "PROVIDERS.md"

# Tier + free-tier limits, verified 2026-09-25 against provider docs or live
# probes (see docs/DECISIONS.md, same date). Update this table when a limit
# changes; the model lists below come from config.json and never need hand edits.
META: dict[str, tuple[str, str]] = {
    "vllm-local": (
        "local",
        "RTX 5090, Qwen3.8-27B W4A16, 32 seqs, 65k ctx, ~397 tok/s aggregate @c32. Owned; no quota.",
    ),
    "embed-local": ("local", "CPU llama.cpp, Qwen3-Embedding-0.6B f16, 1024-dim. Owned; no quota."),
    "nvidia-nim": (
        "strong",
        "40 RPM per key (3 keys, independent pools), no daily cap; 200 RPM on request. "
        "Cold starts up to ~50s on idle models.",
    ),
    "groq": (
        "fast",
        "Free: 30 RPM, 1k RPD, 8k TPM, 200k TPD per model. Cloudflare 1010-blocks clients without a User-Agent.",
    ),
    "openrouter": ("strong", ":free ids only: 20 RPM, 1,000 RPD (>= $10 lifetime purchase on the account)."),
    "hf-router": ("fallback", "~100k credits/month free."),
    "freellmapi": (
        "fallback",
        "Self-hosted aggregator (shared-freellmapi:3001); upstream limits per its own key chain.",
    ),
    "sealion": ("fallback", "AI Singapore free key; ~10 req/window 429s under burst. Includes Nemotron-SEA-LION 120B."),
    "aion": ("fallback", "Free account hits 'Daily token limit exceeded' (429) most days; deep tail only."),
    "gemini": (
        "fast",
        "Flash-class only: ~20 RPD on 3.x Flash, ~500 RPD on Flash-Lite (per project; Google no longer publishes).",
    ),
    "mistral": ("strong", "Experiment tier ~1B tokens/month."),
    "zai": ("fallback", "glm-4.x-flash free at 1 concurrency; 429s at ADA volume."),
    "cerebras": ("fast", "No longer free: $5 / 30-day trial, card required (Aug 2026)."),
    "cloudflare-ai": ("fast", "10,000 neurons/day, no card."),
    "sambanova": ("fast", "20 RPM, 200k tokens/day, no card."),
    "cohere": ("strong", "Trial key: 1,000 calls/month, no card; includes rerank + embed."),
    "moonshot": ("paid", "Retired paid account (2026-06-11). Kimi K3 is free via nvidia-nim."),
    "moonshot-nim-compat": ("shim", "Legacy moonshot/* names over NIM; Kimi K2.6 404s on NIM since 2026-07-13."),
    "anthropic": ("paid", "Paid only; disabled by operator (all-free policy)."),
    "minimax": ("paid", "Disabled by operator; MiniMax M2.7 is free via nvidia-nim / hf-router."),
    "ovhcloud": ("fallback", "Key expired (403)."),
    "siliconflow": ("fallback", "No free models registered on the key."),
    "bazaarlink": ("fallback", "0 successes in 24h (2026-09-15)."),
}


def _models(block: dict) -> list[str]:
    seen: list[str] = []
    for key in block.get("keys", []):
        for m in key.get("models", []):
            if m not in seen:
                seen.append(m)
    return seen


def _aliases(block: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for key in block.get("keys", []):
        out.update(key.get("aliases") or {})
    return out


def render() -> str:
    cfg = json.loads(CONFIG.read_text(encoding="utf-8"))
    dis = json.loads(DISABLED.read_text(encoding="utf-8"))
    active = cfg.get("providers", {})
    parked = {k: v for k, v in dis.get("providers", dis).items() if isinstance(v, dict) and k not in active}
    lines = [
        "# Bifrost providers",
        "",
        "GENERATED by `scripts/render_providers_doc.py` from `bifrost/config.json` and",
        "`bifrost/disabled-providers.json`. Do not hand-edit; the gate (`scripts/gate.py`)",
        "fails when this file is stale. Call a model as `<provider>/<model>` with a",
        "virtual key (`x-bf-vk` or `Authorization: Bearer`).",
        "",
        f"## Active ({len(active)})",
        "",
        "| Provider | Tier | Keys | Models | Limits |",
        "|---|---|---|---|---|",
    ]
    for name, block in active.items():
        tier, limits = META.get(name, ("?", "not recorded -- add to META"))
        aliases = _aliases(block)
        real = [m for m in _models(block) if m not in aliases]
        lines.append(
            f"| `{name}` | {tier} | {len(block.get('keys', []))} | {len(real)} (+{len(aliases)} aliases) | {limits} |"
        )
    lines += ["", "### Models per active provider", ""]
    for name, block in active.items():
        aliases = _aliases(block)
        real = [m for m in _models(block) if m not in aliases]
        lines.append(f"- **{name}**: " + ", ".join(f"`{m}`" for m in real))
        if aliases:
            lines.append("  - aliases: " + ", ".join(f"`{a}` -> `{t}`" for a, t in aliases.items()))
    lines += [
        "",
        f"## Parked ({len(parked)})",
        "",
        "| Provider | Tier | Why parked / how to restore |",
        "|---|---|---|",
    ]
    for name, block in parked.items():
        tier, limits = META.get(name, ("?", ""))
        why = " ".join(str(block.get("_comment", "")).split())
        why = (why[:220] + "...") if len(why) > 220 else why
        lines.append(f"| `{name}` | {tier} | {why or limits} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print("docs/PROVIDERS.md is stale: run python scripts/render_providers_doc.py")
            return 1
        print("docs/PROVIDERS.md up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
